### ISSUE TITLE
Runbook Failure in Central US Region with "Start-ESICollector" Script

### ISSUE THREAD

**Issue by zrahim-cybermsi** [nlepagnez/ESI-PublicContent#11]
Issue Description:

The PowerShell runbook "Start-ESICollector" is encountering failures specifically in the environments of our three customers located in the Central US region. Prior to March 29th, the runbook functioned correctly across all regions where our solution is deployed, including the East US and East US 2 regions. However, after March 29th, the runbook has consistently failed in Central US environments.

The errors include:
1.	Illegal characters in the path.
Split-Path : Illegal characters in path. At line:3486 char:21 + ... $scriptFolder = Split-Path -Parent $MyInvocation.MyCommand.Definition + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ + CategoryInfo : InvalidArgument: ( This sample sc...p-Transcript } :String) [Split-Path], ArgumentException + FullyQualifiedErrorId : ItemExistsArgumentError,Microsoft.PowerShell.Commands.SplitPathCommand
2.	Cannot find drive with the name '<# Disclaimer'.
Job stream details
Push-Location : Cannot find drive. A drive with the name '<# Disclaimer' does not exist. At line:3490 char:5 + Push-Location ($scriptFolder); + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ + CategoryInfo : ObjectNotFound: (<# Disclaimer:String) [Push-Location], DriveNotFoundException + FullyQualifiedErrorId : DriveNotFound,Microsoft.PowerShell.Commands.PushLocationCommand
3.	Configuration file version is outdated.
4.	Processing not in authorized list: 'Online', 'On-Premises'.
5.	Cannot bind argument to parameter 'Path' because it is null.

**Comment by nlepagnez** [comment]
Hi @zrahim-cybermsi,

Sorry for the delay of our answer. 
In the extracted error, I understand that the runbook try to create/find a folder path. This is something reserved for the On-Premise Execution. The ExchangeCollector Script detects if it execute on a Runbook or on a server. 

Beginning this year we found that the method we use to detect that could generate a false detection. In details, we check if a module "Orchestrator" exists On-Premises and in few Automation environments, we found that this check could be true since few month. To very that, you can go to the module part and check that you can find a module containing "Orchestrator".

We implemented a change on this detection in the 2 last versions of the Exchange Collector (since February I think and latest 7.6.0.0 version published last week).

To update that, you can follow the instruction in this link : [https://github.com/nlepagnez/ESI-PublicContent/blob/main/Solutions/ESICollector/OnlineDeployment/Update.md](https://github.com/nlepagnez/ESI-PublicContent/blob/main/Solutions/ESICollector/OnlineDeployment/Update.md). We are developing a system to provide you an auto-update mechanism and we are in the final "Test" stage before entering in the publishing phase.

Concerning the Point 3, this is not a blocker point as we didn't introduced mandatory configuration for the Online part but you can use the same procedure to update the configuration part as it's generally good to be in the latest version.

Concerning Point 4 and 5, I think it's due to errors 1 or 2.

Do not hesitate to come back to us if needed.

Nicolas Lepagnez

**Comment by zrahim-cybermsi** [comment]
Hi @nlepagnez,

Firstly, I want to express our gratitude for providing the updated script. It's been instrumental in resolving the issue across all our customer environments, except for one.

In this particular environment, we're encountering persistent errors, despite implementing the updated script. Here's a breakdown of the errors we're facing:

Error 1: Exception calling "FromBase64String" with "1" argument(s): "Invalid length for a Base-64 char array or string." At line:1521 char:9 + $keyBytes = [Convert]::FromBase64String($sharedKey) + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ + CategoryInfo : NotSpecified: (:) [], MethodInvocationException + FullyQualifiedErrorId : FormatException
Error 2: Exception setting "Key": "Object reference not set to an instance of an object." At line:1524 char:9 + $sha256.Key = $keyBytes + ~~~~~~~~~~~~~~~~~~~~~~~ + CategoryInfo : NotSpecified: (:) [], SetValueInvocationException + FullyQualifiedErrorId : ExceptionWhenSetting

Error 3: Exception calling "ComputeHash" with "1" argument(s): "Object reference not set to an instance of an object." At line:1525 char:9 + $calculatedHash = $sha256.ComputeHash($bytesToHash) + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ + CategoryInfo : NotSpecified: (:) [], MethodInvocationException + FullyQualifiedErrorId : NullReferenceException

Error 4: Exception calling "ToBase64String" with "1" argument(s): "Value cannot be null. Parameter name: inArray" At line:1526 char:9 + $encodedHash = [Convert]::ToBase64String($calculatedHash) + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ + CategoryInfo : NotSpecified: (:) [], MethodInvocationException + FullyQualifiedErrorId : ArgumentNullException

Your insights into these errors and guidance on troubleshooting steps would be invaluable in resolving them promptly. We kindly request your assistance in diagnosing the root cause and providing recommendations for resolution based on your expertise.

Thank you for your continued support and collaboration.

**Comment by nlepagnez** [comment]
Hi @zrahim-cybermsi,

If I understand well, this is because the system is not able to use the Log Analytics Shared Key from the Config file. 

Did you correctly fill the following parameters in the configuration variable for this runbook : 
![image](https://github.com/nlepagnez/ESI-PublicContent/assets/2814429/37a2e9ed-482e-4814-ae53-bc08d4fd9f0f)

**Comment by zrahim-cybermsi** [comment]
Hi @nlepagnez 

Thank you for your support. I updated the Config file with the required variables, and I'm pleased to inform you that the issue has been resolved. Your assistance is greatly appreciated.
