### ISSUE TITLE
Failed to Assign Exchange Online Permissions - Conversion Error 'Edm.Guid'

### ISSUE THREAD

**Issue by zrahim-cybermsi** [nlepagnez/ESI-PublicContent#7]
**Issue Summary:**
When running the permission script "ExchangeOnlinePermSetup.ps1", I encountered an issue while trying to create a service principal app role assignment. The error message suggests a problem with converting an empty string to the expected type 'Edm.Guid'. The script successfully assigned the following permissions:

Group.Read.All
User.Read.All
AuditLog.Read.All

However, it failed to assign permissions for connecting the application with Exchange Online.

The script successfully assigned the permissions for Microsoft Graph but failed with the following error when attempting to assign permissions for Exchange Online:

New-MgServicePrincipalAppRoleAssignment_CreateExpanded: C:\Users\Adil\Desktop\updated4.ps1:43
Line | 43 | New-MgServicePrincipalAppRoleAssignment -ServicePrincipalId $MI_ID ...
     | Cannot convert the literal '' to the expected type 'Edm.Guid'. Status: 400 (BadRequest) ErrorCode: Request_BadRequest ...

**Screenshot:**
![MicrosoftTeams-image (4)](https://github.com/nlepagnez/ESI-PublicContent/assets/116695308/856339ae-df44-46f8-b64f-d694a6da4a2b)

**Comment by nlepagnez** [comment]
Hello @zrahim-cybermsi, I'm sorry for the delay of our answer due to Christmas holidays. 

The error you have indicate that the ResourceID of "Exchange Online" is not found by the script. 
In the Entra ID Portal, in "Enterprise Application", can you confirm me that you can find "Exchange Online" with the id "00000002-0000-0ff1-ce00-000000000000" ?
![image](https://github.com/nlepagnez/ESI-PublicContent/assets/2814429/8f98fbd5-b42c-4db1-acf8-e090809b533a)

**Comment by nlepagnez** [comment]
Hello @zrahim-cybermsi, do you have time to check the Application GUID ? Or Can I archive this issue ?

**Comment by zrahim-cybermsi** [comment]
Please archive the issue, I resolved the issue by creating another permissions script. Thanks

**Comment by nlepagnez** [comment]
Thank you for your answer.
